name = "anibinge-frontend"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "6f6ab5f24a17f87a23774eba28ce5a67"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
